
export enum ReleaseStatus {

  RUNNING = "RUNNING",
  SUCCEED = "SUCCEED",
  FAILED = "FAILED",
  ROLLBACK_RUNNING = "ROLLBACK_RUNNING",
  ROLLBACK_SUCCEED = "ROLLBACK_SUCCEED",
  ROLLBACK_FAILED = "ROLLBACK_FAILED"

}
